image: registry.gitlab.com/gbraad/fedora:24

before_script:
  - dnf install -y git wget flatpak flatpak-builder make bzip2 elfutils

pages:
  stage: build
  script:
    - DIR=`pwd`
    - mkdir -p /working
    - cd /working
    - $DIR/build.sh
    - mkdir -p $DIR/public
    - cp ./spotify-app/*.flatpak $DIR/public
  artifacts:
    paths:
      - public

